### ISSUE TITLE
Can't compile lib

### ISSUE THREAD

**Issue by IchKG** [luksal/ESP32-DMX-RX#11]
Hi 
I'm trying to receive DMX and send 9 channels through ESP-NOW.
I bought a SparkFun DMX Thing and connected it to an ESP32 Thing (not plus)
First I tried the SparkFun DMX Lib but got the same issues as several other with shifted data or complete wrong data.
Because of the issues forum in that lib I found luksal's and want to give it a try but I can't even compile it. I downloaded it from github as zip and used the import lib by zip function in arduino IDE (1.8.12).
When I try to compile the SimpleRX example I get "error: 'uint8_t' does not name a type" and several others. What am I doing wrong?

A few errors from output (for full output see https://pastebin.com/MAa2btf6):
`In file included from C:\Users\markus\Documents\Arduino\libraries\ESP32DMXRX\src\dmx.cpp:1:0:

C:\Users\markus\Documents\Arduino\libraries\ESP32DMXRX\src/dmx.h:9:16: error: "uint8_t" does not name a type

         static uint8_t Read(uint16_t channel);              // returns the dmx value for the givven address (values from 1 to 512)

                ^

C:\Users\markus\Documents\Arduino\libraries\ESP32DMXRX\src/dmx.h:16:16: error: "QueueHandle_t" does not name a type

         static QueueHandle_t dmx_rx_queue;                  // queue for uart rx events

                ^

C:\Users\markus\Documents\Arduino\libraries\ESP32DMXRX\src/dmx.h:18:16: error: "SemaphoreHandle_t" does not name a type

         static SemaphoreHandle_t sync_dmx;                  // semaphore for syncronising access to dmx array

                ^

C:\Users\markus\Documents\Arduino\libraries\ESP32DMXRX\src/dmx.h:22:16: error: "uint16_t" does not name a type

         static uint16_t current_rx_addr;                    // last received dmx channel

                ^

C:\Users\markus\Documents\Arduino\libraries\ESP32DMXRX\src\dmx.cpp:25:15: error: "uint16_t DMX::current_rx_addr" is not a static data member of "class DMX"

 uint16_t DMX::current_rx_addr = 0;

               ^

C:\Users\markus\Documents\Arduino\libraries\ESP32DMXRX\src\dmx.cpp:29:26: error: "uint8_t DMX::dmx_data [513]" is not a static data member of "class DMX"

 uint8_t DMX::dmx_data[513];

                          ^

C:\Users\markus\Documents\Arduino\libraries\ESP32DMXRX\src\dmx.cpp: In static member function "static void DMX::Initialize()":

C:\Users\markus\Documents\Arduino\libraries\ESP32DMXRX\src\dmx.cpp:54:72: error: "dmx_rx_queue" was not declared in this scope

     uart_driver_install(DMX_UART_NUM, BUF_SIZE * 2, BUF_SIZE * 2, 20, &dmx_rx_queue, 0);

                                                                        ^
exit status 1
Error compiling for board ESP32 Dev Module.
`

**Comment by luksal** [comment]
Looks like there are some problems regarding your build environment. You can try adding  `#include <stdint.h>` on top of the `dmx.cpp` file inside the src folder.

**Comment by IchKG** [comment]
> Looks like there are some problems regarding your build environment. You can try adding `#include <stdint.h>` on top of the `dmx.cpp` file inside the src folder.

Yes that did the trick, I added 
 `#include <stdint.h>`
 `#include <stdstring.h> // for bzero function`
on top of dmx.cpp and moved the include of dmx.h down to be the last one because dmx.h needed queue.h to be included first.
Now it is working fine and its the first library that worked and got all 512 Channels right and I've tested a few. Thank's @luksal for your lib.
Edit: including Arduino.h on top of dmx.cpp is another option

**Comment by sasodoma** [comment]
Hello, I would like to ask whether this is a problem with this library, a problem with my IDE or is it like this by design and won't be changed. I ran across the same problem today and it seems strange to me that a fix is known but not implemented in the code. The only two reasons I could think of is that something is wrong with my Arduino installation, or that the Arduino IDE is simply incapable of correctly compiling this without including some extra stuff. Is this problem something that will be fixed or should I fork this library and keep a separate version of it that works with the Arduino IDE?

**Comment by luksal** [comment]
I'm not using the library inside the Arduino environment. You are free to create a pull request, so that I can merge the fixes that are needed for Arduino.
