### ISSUE TITLE
Setting a DMX address for the receiver module

### ISSUE THREAD

**Issue by FabioLazzar8** [luksal/ESP32-DMX-RX#16]
Hi, i need to use the receiver device on a stage were there is already a dmx line and some fixture. So i would need to set an address to control individually the esp32 fixture. Is it possible or i would use another lib?

thank you in advance

**Comment by luksal** [comment]
The `uint8_t DMX::dmx_data[513]` array contains the whole DMX universe.
So with  `DMX::Read(uint16_t channel)` you can get any channel (starting with 1, end ending with 512) you need.

If you want to use a "start address" you can use something like this pseudocode for RGB LED controller:

```C
#define CHANNEL_RED 0
#define CHANNEL_GREEN 1
#define CHANNEL_BLUE 2

uint16_t start_address = 64; // change to anything you like

while(1)
{
  uint8_t value_for_red_led = DMX::Read(start_address + CHANNEL_RED);
  uint8_t value_for_green_led = DMX::Read(start_address + CHANNEL_GREEN);
  uint8_t value_for_blue_led = DMX::Read(start_address + CHANNEL_BLUE);

  // use your set_led functions here
}

```

Hope this helps to solve your problem.
