### ISSUE TITLE
Wiring diagram between ESP32 and other modules

### ISSUE THREAD

**Issue by LiutukasO** [luksal/ESP32-DMX-RX#17]
I like your project.
It would be great if you added connection diagrams to the documentation.
I have the required components, but your example code doesn't work for me. And I don't have an oscilloscope or other necessary measure devices. So I can’t find a reason. Probably my problem with wiring. But I have no way to check. The diagram would help me at least check the connections.
Thank you.

**Comment by luksal** [comment]
You can find lots of examples on the net how to connect the serial port of the ESP32 to a RS485 bus transreceiver.
This "library" was never intended to be a plug and play library and should rather serve as food for thought for others who face the same problem as I did. Therefore I did not plan to create corresponding documentation.
But you are welcome to create it and submit it as a pull request. I will then merge it into the repository.
