### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by gabgabe** [luksal/ESP32-DMX-RX#9]
Am I missing some files? I'm using espressif core, can't compile. What libraries are you using here?

#include <dmx.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/queue.h"
#include "driver/uart.h"

thank you !

**Comment by luksal** [comment]
dmx.h -> this repository

other files: esp-idf

Please look at closed issues, this was handled before
